### ISSUE TITLE
website vulnerability

### ISSUE THREAD

**Issue by debragail** [stripe/stripe.github.io#4]
hi

i want to report a potential website vulnerability.  where do i do that?

**Comment by debragail** [comment]
@brandur-stripe

**Comment by debragail** [comment]
@bryan-stripe

**Comment by rlk-stripe** [comment]
@debragail Please email us at security@stripe.com.  You can find more info (and our PGP key if you're so inclined) at https://stripe.com/docs/security/stripe#disclosure-and-reward-program

Thanks!
